CMake: Rework system/arch handing
- Add Windows and Darwin arm64 builds
- Exclude arm64 from test execution

diff --git a/.github/workflows/buildmgr.yml b/.github/workflows/buildmgr.yml
--- a/.github/workflows/buildmgr.yml
+++ b/.github/workflows/buildmgr.yml
@@ -69,27 +69,17 @@ jobs:
 
       # https://github.com/Open-CMSIS-Pack/devtools-build-action
       - name: Build
-        uses: Open-CMSIS-Pack/devtools-build-action@v1.2
+        uses: Open-CMSIS-Pack/devtools-build-action@arm64
         id: devtools-build
         with:
           target: cbuildgen
           arch: ${{ matrix.arch }}
 
-      - name: Rename binary to be integrated to the installer (macOS, Linux)
-        if: ${{ startsWith(matrix.runs_on, 'macos') || startsWith(matrix.runs_on, 'ubuntu') }}
-        run: mv cbuildgen cbuildgen${{ matrix.binary_extension }}
-        working-directory: build/tools/buildmgr/cbuildgen/${{ matrix.target }}/Release
-
-      - name: Rename binary to be integrated to the installer (Windows)
-        if: ${{ startsWith(matrix.runs_on, 'windows') }}
-        run: mv cbuildgen.exe cbuildgen${{ matrix.binary_extension }}
-        working-directory: build/tools/buildmgr/cbuildgen/${{ matrix.target }}/Release
-
       - name: Archive cbuildgen
         uses: actions/upload-artifact@v3
         with:
           name: cbuildgen-${{ matrix.target }}-${{ matrix.arch }}
-          path: ./build/tools/buildmgr/cbuildgen/${{ matrix.target }}/Release/cbuildgen${{ matrix.binary_extension }}
+          path: ./build/tools/buildmgr/cbuildgen/${{ matrix.target }}-${{ matrix.arch }}/Release/cbuildgen${{ matrix.binary_extension }}
           retention-days: ${{ needs.setup.outputs.retention_days }}
           if-no-files-found: error
 
@@ -209,29 +199,42 @@ jobs:
           mkdir -p tools/buildmgr/cbuildgen/distribution/bin
           mkdir -p tools/buildmgr/cbuildgen/distribution/doc
 
-      - name: Download cbuildgen linux amd64
+      - name: Download cbuildgen linux-amd64
         uses: actions/download-artifact@v3
         with:
-          name: cbuildgen-linux64-amd64
+          name: cbuildgen-linux-amd64
           path: tools/buildmgr/cbuildgen/distribution/bin/
 
-      - name: Download cbuildgen linux arm64
+      - name: Download cbuildgen linux-arm64
         uses: actions/download-artifact@v3
         with:
-          name: cbuildgen-linux64-arm64
+          name: cbuildgen-linux-arm64
           path: tools/buildmgr/cbuildgen/distribution/bin/
 
-      - name: Download cbuildgen macos
+      - name: Download cbuildgen macos-amd64
         if: ${{ !github.event.repository.private }}
         uses: actions/download-artifact@v3
         with:
-          name: cbuildgen-darwin64-amd64
+          name: cbuildgen-darwin-amd64
           path: tools/buildmgr/cbuildgen/distribution/bin/
 
-      - name: Download cbuildgen windows
+      - name: Download cbuildgen macos-arm64
+        if: ${{ !github.event.repository.private }}
         uses: actions/download-artifact@v3
         with:
-          name: cbuildgen-windows64-amd64
+          name: cbuildgen-darwin-arm64
+          path: tools/buildmgr/cbuildgen/distribution/bin/
+
+      - name: Download cbuildgen windows-amd64
+        uses: actions/download-artifact@v3
+        with:
+          name: cbuildgen-windows-amd64
+          path: tools/buildmgr/cbuildgen/distribution/bin/
+
+      - name: Download cbuildgen windows-arm64
+        uses: actions/download-artifact@v3
+        with:
+          name: cbuildgen-windows-arm64
           path: tools/buildmgr/cbuildgen/distribution/bin/
 
       - name: Adding execution permission to the binaries
@@ -301,7 +304,7 @@ jobs:
       GCC_TOOLCHAIN_ROOT: ${{ github.workspace }}/${{ matrix.toolchain_root }}
       CI_ARCH: ${{ matrix.arch }}
     strategy:
-      fail-fast: true
+      #fail-fast: true
       matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
     steps:
       - name: Install macos deps
@@ -380,17 +383,19 @@ jobs:
 
       # https://github.com/Open-CMSIS-Pack/devtools-build-action
       - name: Build CbuildUnitTests
-        uses: Open-CMSIS-Pack/devtools-build-action@v1.2
+        uses: Open-CMSIS-Pack/devtools-build-action@arm64
         with:
           target: CbuildUnitTests
           build_type: Debug
           arch: ${{ matrix.arch }}
 
       - name: Run CbuildUnitTests
+        if: matrix.arch != 'arm64'
         run: ctest -V -R CbuildUnitTests
         working-directory: build
 
       - name: Archive unittest
+        if: always() && (matrix.arch != 'arm64')
         uses: actions/upload-artifact@v3
         with:
           name: unit_test_result-${{ matrix.target }}-${{ matrix.arch }}
@@ -400,7 +405,7 @@ jobs:
 
       # https://github.com/Open-CMSIS-Pack/devtools-build-action
       - name: Build CbuildIntegTests
-        uses: Open-CMSIS-Pack/devtools-build-action@v1.1
+        uses: Open-CMSIS-Pack/devtools-build-action@arm64
         with:
           target: CbuildIntegTests
           build_type: Debug
@@ -408,42 +413,30 @@ jobs:
 
       - name: Run Cbuild Integration Tests (excl. AC5, AC6, MultiTargetAC6Tests) for Linux amd64
         if: ${{ startsWith(matrix.runs_on, 'ubuntu') && matrix.arch == 'amd64' }}
-        env:
-          target: ${{ matrix.target }}
-          arch: ${{ matrix.arch }}
-        run: ./tools/buildmgr/test/integrationtests/${target}/Debug/CbuildIntegTests --gtest_filter=-*AC5*:*AC6*:*MultiTargetAC6Tests* --gtest_output=xml:test_reports/cbuildintegtests-report-${target}-${arch}.xml
+        run: ./tools/buildmgr/test/integrationtests/${{ matrix.target }}-${{ matrix.arch }}/Debug/CbuildIntegTests --gtest_filter=-*AC5*:*AC6*:*MultiTargetAC6Tests* --gtest_output=xml:test_reports/cbuildintegtests-report-${{ matrix.target }}-${{ matrix.arch }}.xml
         working-directory: build
 
       - name: Run Cbuild Integration Tests (excl. AC5, AC6, MultiTargetAC6Tests) for Linux arm64
         if: ${{ startsWith(matrix.runs_on, 'ubuntu') && matrix.arch == 'arm64' }}
-        env:
-          target: ${{ matrix.target }}
-          arch: ${{ matrix.arch }}
-        run: /usr/bin/qemu-aarch64 -L /usr/aarch64-linux-gnu ./tools/buildmgr/test/integrationtests/${target}/Debug/CbuildIntegTests --gtest_filter=-*AC5*:*AC6*:*MultiTargetAC6Tests* --gtest_output=xml:test_reports/cbuildintegtests-report-${target}-${arch}.xml
+        run: /usr/bin/qemu-aarch64 -L /usr/aarch64-linux-gnu ./tools/buildmgr/test/integrationtests/${{ matrix.target }}-${{ matrix.arch }}/Debug/CbuildIntegTests --gtest_filter=-*AC5*:*AC6*:*MultiTargetAC6Tests* --gtest_output=xml:test_reports/cbuildintegtests-report-${{ matrix.target }}-${{ matrix.arch }}.xml
         working-directory: build
 
       - name: Run Cbuild Integration Tests (excl. DebPkgTests, AC5, AC6, MultiTargetAC6Tests) for macOS
-        if: ${{ startsWith(matrix.runs_on, 'macos') }}
-        env:
-          target: ${{ matrix.target }}
-          arch: ${{ matrix.arch }}
-        run: ./tools/buildmgr/test/integrationtests/${target}/Debug/CbuildIntegTests --gtest_filter=-*DebPkgTests*:*AC5*:*AC6*:*MultiTargetAC6Tests* --gtest_output=xml:test_reports/cbuildintegtests-report-${target}-${arch}.xml
+        if: ${{ startsWith(matrix.runs_on, 'macos') && matrix.arch == 'amd64' }}
+        run: ./tools/buildmgr/test/integrationtests/${{ matrix.target }}-${{ matrix.arch }}/Debug/CbuildIntegTests --gtest_filter=-*DebPkgTests*:*AC5*:*AC6*:*MultiTargetAC6Tests* --gtest_output=xml:test_reports/cbuildintegtests-report-${{ matrix.target }}-${{ matrix.arch }}.xml
         working-directory: build
 
       - name: Run Cbuild Integration Tests (excl. DebPkgTests, AC5, AC6, MultiTargetAC6Tests) for Windows
-        if: ${{ startsWith(matrix.runs_on, 'windows') }}
-        env:
-          target: ${{ matrix.target }}
-          arch: ${{ matrix.arch }}
-        # For some reason the env variable usage $Env:target does not work properly.
-        run: .\tools\buildmgr\test\integrationtests\windows64\Debug\CbuildIntegTests.exe --gtest_filter=-*DebPkgTests*:*AC5*:*AC6*:*MultiTargetAC6Tests* --gtest_output=xml:test_reports/cbuildintegtests-report-${target}-${arch}.xml
+        if: ${{ startsWith(matrix.runs_on, 'windows') && matrix.arch == 'amd64' }}
+        run: .\tools\buildmgr\test\integrationtests\${{ matrix.target }}-${{ matrix.arch }}\Debug\CbuildIntegTests.exe --gtest_filter=-*DebPkgTests*:*AC5*:*AC6*:*MultiTargetAC6Tests* --gtest_output=xml:test_reports/cbuildintegtests-report-${{ matrix.target }}-${{ matrix.arch }}.xml
         working-directory: build
 
       - name: Archive Cbuild Integration Tests
+        if: always() && ((matrix.arch == 'amd64') || (startsWith(matrix.runs_on, 'ubuntu')))
         uses: actions/upload-artifact@v3
         with:
           name: integ_test_result-${{ matrix.target }}-${{ matrix.arch }}
-          path: ./build/test_reports/cbuildintegtests-*.xml
+          path: ./build/test_reports/cbuildintegtests-report-${{ matrix.target }}-${{ matrix.arch }}.xml
           retention-days: ${{ needs.setup.outputs.retention_days }}
           if-no-files-found: error
 
@@ -505,9 +498,9 @@ jobs:
         run: |
           cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON ..
           cmake --build . --target CbuildUnitTests
-          ./tools/buildmgr/test/unittests/linux64/Debug/CbuildUnitTests --gtest_output=xml:test_reports/cbuildunittests-report-linux64-amd64.xml
+          ./tools/buildmgr/test/unittests/linux-amd64/Debug/CbuildUnitTests --gtest_output=xml:test_reports/cbuildunittests-report-linux-amd64.xml
           cmake --build . --target CbuildIntegTests
-          ./tools/buildmgr/test/integrationtests/linux64/Debug/CbuildIntegTests --gtest_filter=-*AC5*:*AC6*:*MultiTargetAC6Tests*:*DebPkgTests*:*InstallerTests* --gtest_output=xml:test_reports/cbuildintegtests-report-linux64-amd64.xml
+          ./tools/buildmgr/test/integrationtests/linux-amd64/Debug/CbuildIntegTests --gtest_filter=-*AC5*:*AC6*:*MultiTargetAC6Tests*:*DebPkgTests*:*InstallerTests* --gtest_output=xml:test_reports/cbuildintegtests-report-linux-amd64.xml
         working-directory: build
 
       - name: Get retention days
@@ -519,7 +512,7 @@ jobs:
         if: (github.event_name == 'push')
         uses: actions/upload-artifact@v3
         with:
-          name: unit_test_result-linux64-amd64
+          name: unit_test_result-linux-amd64
           path: ./build/test_reports/cbuildunittests-*.xml
           retention-days: ${{ steps.var.outputs.retention_days }}
           if-no-files-found: error
@@ -528,7 +521,7 @@ jobs:
         if: (github.event_name == 'push')
         uses: actions/upload-artifact@v3
         with:
-          name: integ_test_result-linux64-amd64
+          name: integ_test_result-linux-amd64
           path: ./build/test_reports/cbuildintegtests-*.xml
           retention-days: ${{ steps.var.outputs.retention_days }}
           if-no-files-found: error
@@ -649,60 +642,12 @@ jobs:
         shell: bash
         run: |
           ${{ github.workspace }}/cbuild/bin/cbuildgen | grep "(cbuildgen): Build Process Manager"
+
   test-results-preparation:
     name: "Publish Tests Results"
     needs: [ tests ]
     runs-on: ubuntu-22.04
     steps:
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.8
-
-      - name: Download unit test report windows
-        uses: actions/download-artifact@v3
-        with:
-          name: unit_test_result-windows64-amd64
-          path: testreports/
-
-      - name: Download unit test report linux amd64
-        uses: actions/download-artifact@v3
-        with:
-          name: unit_test_result-linux64-amd64
-          path: testreports/
-
-      - name: Download unit test report linux arm64
-        uses: actions/download-artifact@v3
-        with:
-          name: unit_test_result-linux64-arm64
-          path: testreports/
-
-      - name: Download unit test report macos
-        if: ${{ !github.event.repository.private }}
-        uses: actions/download-artifact@v3
-        with:
-          name: unit_test_result-darwin64-amd64
-          path: testreports/
-
-      - name: Download integ test report windows
-        uses: actions/download-artifact@v3
-        with:
-          name: integ_test_result-windows64-amd64
-          path: testreports/
-
-      - name: Download integ test report linux amd64
-        uses: actions/download-artifact@v3
-        with:
-          name: integ_test_result-linux64-amd64
-          path: testreports/
-
-      - name: Download integ test report macos
-        if: ${{ !github.event.repository.private }}
-        uses: actions/download-artifact@v3
-        with:
-          name: integ_test_result-darwin64-amd64
-          path: testreports/
-
       - name: Event File
         uses: actions/upload-artifact@v3
         with:
